<?php

use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->truncate();
        $countries = [
			['prefix' => 'US', 'name' => 'United States',"currency"=>'USD','currency_is_active'=>1],
			['prefix' => 'CA', 'name' => 'Canada',"currency"=>'CAD','currency_is_active'=>0],
			['prefix' => 'AF', 'name' => 'Afghanistan',"currency"=>'AFN','currency_is_active'=>0],
			['prefix' => 'AL', 'name' => 'Albania',"currency"=>'ALL','currency_is_active'=>0],
			['prefix' => 'DZ', 'name' => 'Algeria',"currency"=>'DZD','currency_is_active'=>0],
			['prefix' => 'AS', 'name' => 'American Samoa',"currency"=>'USD','currency_is_active'=>1],
			['prefix' => 'AD', 'name' => 'Andorra',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'AO', 'name' => 'Angola',"currency"=>'AOA','currency_is_active'=>0],
			['prefix' => 'AI', 'name' => 'Anguilla',"currency"=>'XCD','currency_is_active'=>0],
			['prefix' => 'AG', 'name' => 'Antigua and Barbuda',"currency"=>'XCD','currency_is_active'=>0],
			['prefix' => 'AR', 'name' => 'Argentina',"currency"=>'ARS','currency_is_active'=>0],
			['prefix' => 'AM', 'name' => 'Armenia',"currency"=>'AMD','currency_is_active'=>0],
			['prefix' => 'AW', 'name' => 'Aruba',"currency"=>'AWG','currency_is_active'=>0],
			['prefix' => 'AU', 'name' => 'Australia',"currency"=>'AUD','currency_is_active'=>0],
			['prefix' => 'AT', 'name' => 'Austria',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'AZ', 'name' => 'Azerbaijan',"currency"=>'AZN','currency_is_active'=>0],
			['prefix' => 'BS', 'name' => 'Bahamas',"currency"=>'BSD','currency_is_active'=>0],
			['prefix' => 'BH', 'name' => 'Bahrain',"currency"=>'BHD','currency_is_active'=>0],
			['prefix' => 'BD', 'name' => 'Bangladesh',"currency"=>'BDT','currency_is_active'=>0],
			['prefix' => 'BB', 'name' => 'Barbados',"currency"=>'BBD','currency_is_active'=>0],
			['prefix' => 'BY', 'name' => 'Belarus',"currency"=>'BYN','currency_is_active'=>0],
			['prefix' => 'BE', 'name' => 'Belgium',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'BZ', 'name' => 'Belize',"currency"=>'BZD','currency_is_active'=>0],
			['prefix' => 'BJ', 'name' => 'Benin',"currency"=>'XOF','currency_is_active'=>0],
			['prefix' => 'BM', 'name' => 'Bermuda',"currency"=>'BMD','currency_is_active'=>0],
			['prefix' => 'BT', 'name' => 'Bhutan',"currency"=>'BTN','currency_is_active'=>0],
			['prefix' => 'BO', 'name' => 'Bolivia',"currency"=>'BOB','currency_is_active'=>0],
			['prefix' => 'BA', 'name' => 'Bosnia and Herzegovina',"currency"=>'BAM','currency_is_active'=>0],
			['prefix' => 'BW', 'name' => 'Botswana',"currency"=>'BWP','currency_is_active'=>0],
			['prefix' => 'BR', 'name' => 'Brazil',"currency"=>'BRL','currency_is_active'=>0],
			['prefix' => 'BN', 'name' => 'Brunei Darussalam',"currency"=>'BND','currency_is_active'=>0],
			['prefix' => 'BG', 'name' => 'Bulgaria',"currency"=>'BGN','currency_is_active'=>0],
			['prefix' => 'BF', 'name' => 'Burkina Faso',"currency"=>'XOF','currency_is_active'=>0],
			['prefix' => 'BI', 'name' => 'Burundi',"currency"=>'BIF','currency_is_active'=>0],
			['prefix' => 'KH', 'name' => 'Cambodia',"currency"=>'KHR','currency_is_active'=>0],
			['prefix' => 'CM', 'name' => 'Cameroon',"currency"=>'XAF','currency_is_active'=>0],
			['prefix' => 'CV', 'name' => 'Cape Verde',"currency"=>'CVE','currency_is_active'=>0],
			['prefix' => 'KY', 'name' => 'Cayman Islands',"currency"=>'KYD','currency_is_active'=>0],
			['prefix' => 'CF', 'name' => 'Central African Republic',"currency"=>'XAF','currency_is_active'=>0],
			['prefix' => 'TD', 'name' => 'Chad',"currency"=>'XAF','currency_is_active'=>0],
			['prefix' => 'CL', 'name' => 'Chile',"currency"=>'CLP','currency_is_active'=>0],
			['prefix' => 'CN', 'name' => 'China',"currency"=>'CNY','currency_is_active'=>0],
			['prefix' => 'CX', 'name' => 'Christmas Island',"currency"=>'AUD','currency_is_active'=>0],
			['prefix' => 'CC', 'name' => 'Cocos (Keeling) Islands',"currency"=>'AUD','currency_is_active'=>0],
			['prefix' => 'CO', 'name' => 'Colombia',"currency"=>'COP','currency_is_active'=>0],
			['prefix' => 'KM', 'name' => 'Comoros',"currency"=>'KMF','currency_is_active'=>0],
			['prefix' => 'CG', 'name' => 'Congo',"currency"=>'XAF','currency_is_active'=>0],
			['prefix' => 'CK', 'name' => 'Cook Islands',"currency"=>'','currency_is_active'=>0],
			['prefix' => 'CR', 'name' => 'Costa Rica',"currency"=>'CRC','currency_is_active'=>0],
			['prefix' => 'HR', 'name' => 'Croatia',"currency"=>'HRK','currency_is_active'=>0],
			['prefix' => 'CU', 'name' => 'Cuba',"currency"=>'CUP','currency_is_active'=>0],
			['prefix' => 'CY', 'name' => 'Cyprus',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'CZ', 'name' => 'Czech Republic',"currency"=>'CZK','currency_is_active'=>0],
			['prefix' => 'CD', 'name' => 'Democratic Republic of Congo',"currency"=>'CDF','currency_is_active'=>0],
			['prefix' => 'DK', 'name' => 'Denmark',"currency"=>'DKK','currency_is_active'=>0],
			['prefix' => 'DJ', 'name' => 'Djibouti',"currency"=>'DJF','currency_is_active'=>0],
			['prefix' => 'DM', 'name' => 'Dominica',"currency"=>'XCD','currency_is_active'=>0],
			['prefix' => 'DO', 'name' => 'Dominican Republic',"currency"=>'DOP','currency_is_active'=>0],
			['prefix' => 'TP', 'name' => 'East Timor',"currency"=>'USD','currency_is_active'=>1],
			['prefix' => 'EC', 'name' => 'Ecudaor',"currency"=>'','currency_is_active'=>0],
			['prefix' => 'EG', 'name' => 'Egypt',"currency"=>'EGP','currency_is_active'=>1],
			['prefix' => 'SV', 'name' => 'El Salvador',"currency"=>'USD','currency_is_active'=>1],
			['prefix' => 'GQ', 'name' => 'Equatorial Guinea',"currency"=>'XAF','currency_is_active'=>0],
			['prefix' => 'ER', 'name' => 'Eritrea',"currency"=>'ERN','currency_is_active'=>0],
			['prefix' => 'EE', 'name' => 'Estonia',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'ET', 'name' => 'Ethiopia',"currency"=>'ETB','currency_is_active'=>0],
			['prefix' => 'FK', 'name' => 'Falkland Islands (Malvinas)',"currency"=>'FKP','currency_is_active'=>0],
			['prefix' => 'FO', 'name' => 'Faroe Islands',"currency"=>'','currency_is_active'=>0],
			['prefix' => 'FJ', 'name' => 'Fiji',"currency"=>'FJD','currency_is_active'=>0],
			['prefix' => 'FI', 'name' => 'Finland',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'FR', 'name' => 'France',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'FX', 'name' => 'France, Metropolitan',"currency"=>'','currency_is_active'=>0],
			['prefix' => 'GF', 'name' => 'French Guiana',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'PF', 'name' => 'French Polynesia',"currency"=>'XPF','currency_is_active'=>0],
			['prefix' => 'GA', 'name' => 'Gabon',"currency"=>'XAF','currency_is_active'=>0],
			['prefix' => 'GM', 'name' => 'Gambia',"currency"=>'GMD','currency_is_active'=>0],
			['prefix' => 'GE', 'name' => 'Georgia',"currency"=>'GEL','currency_is_active'=>0],
			['prefix' => 'DE', 'name' => 'Germany',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'GH', 'name' => 'Ghana',"currency"=>'GHS','currency_is_active'=>0],
			['prefix' => 'GI', 'name' => 'Gibraltar',"currency"=>'GIP','currency_is_active'=>0],
			['prefix' => 'GR', 'name' => 'Greece',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'GL', 'name' => 'Greenland',"currency"=>'DKK','currency_is_active'=>0],
			['prefix' => 'GD', 'name' => 'Grenada',"currency"=>'XCD','currency_is_active'=>0],
			['prefix' => 'GP', 'name' => 'Guadeloupe',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'GU', 'name' => 'Guam',"currency"=>'USD','currency_is_active'=>1],
			['prefix' => 'GT', 'name' => 'Guatemala',"currency"=>'GTQ','currency_is_active'=>0],
			['prefix' => 'GN', 'name' => 'Guinea',"currency"=>'GNF','currency_is_active'=>0],
			['prefix' => 'GW', 'name' => 'Guinea-Bissau',"currency"=>'XOF','currency_is_active'=>0],
			['prefix' => 'GY', 'name' => 'Guyana',"currency"=>'GYD','currency_is_active'=>0],
			['prefix' => 'HT', 'name' => 'Haiti',"currency"=>'HTG','currency_is_active'=>0],
			['prefix' => 'HN', 'name' => 'Honduras',"currency"=>'HNL','currency_is_active'=>0],
			['prefix' => 'HK', 'name' => 'Hong Kong',"currency"=>'HKD','currency_is_active'=>0],
			['prefix' => 'HU', 'name' => 'Hungary',"currency"=>'HUF','currency_is_active'=>0],
			['prefix' => 'IS', 'name' => 'Iceland',"currency"=>'ISK','currency_is_active'=>0],
			['prefix' => 'IN', 'name' => 'India',"currency"=>'INR','currency_is_active'=>0],
			['prefix' => 'ID', 'name' => 'Indonesia',"currency"=>'IDR','currency_is_active'=>0],
			['prefix' => 'IR', 'name' => 'Iran',"currency"=>'IRR','currency_is_active'=>0],
			['prefix' => 'IQ', 'name' => 'Iraq',"currency"=>'IQD','currency_is_active'=>0],
			['prefix' => 'IE', 'name' => 'Ireland',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'IL', 'name' => 'Israel',"currency"=>'ILS','currency_is_active'=>0],
			['prefix' => 'IT', 'name' => 'Italy',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'JM', 'name' => 'Jamaica',"currency"=>'JMD','currency_is_active'=>0],
			['prefix' => 'JP', 'name' => 'Japan',"currency"=>'JPY','currency_is_active'=>0],
			['prefix' => 'JO', 'name' => 'Jordan',"currency"=>'JOD','currency_is_active'=>0],
			['prefix' => 'KZ', 'name' => 'Kazakhstan',"currency"=>'KZT','currency_is_active'=>0],
			['prefix' => 'KE', 'name' => 'Kenya',"currency"=>'KES','currency_is_active'=>0],
			['prefix' => 'KI', 'name' => 'Kiribati',"currency"=>'AUD','currency_is_active'=>0],
			['prefix' => 'KP', 'name' => 'North Korea',"currency"=>'KPW','currency_is_active'=>0],
			['prefix' => 'KR', 'name' => 'South Korea',"currency"=>'KRW','currency_is_active'=>0],
			['prefix' => 'KW', 'name' => 'Kuwait',"currency"=>'KWD','currency_is_active'=>0],
			['prefix' => 'KG', 'name' => 'Kyrgyzstan',"currency"=>'KGS','currency_is_active'=>0],
			['prefix' => 'LA', 'name' => 'Lao People\'s Democratic Republic',"currency"=>'LAK','currency_is_active'=>0],
			['prefix' => 'LV', 'name' => 'Latvia',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'LB', 'name' => 'Lebanon',"currency"=>'LBP','currency_is_active'=>0],
			['prefix' => 'LS', 'name' => 'Lesotho',"currency"=>'LSL','currency_is_active'=>0],
			['prefix' => 'LR', 'name' => 'Liberia',"currency"=>'LRD','currency_is_active'=>0],
			['prefix' => 'LY', 'name' => 'Libyan',"currency"=>'LYD','currency_is_active'=>0],
			['prefix' => 'LI', 'name' => 'Liechtenstein',"currency"=>'CHF','currency_is_active'=>0],
			['prefix' => 'LT', 'name' => 'Lithuania',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'LU', 'name' => 'Luxembourg',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'MO', 'name' => 'Macau',"currency"=>'MOP','currency_is_active'=>0],
			['prefix' => 'MK', 'name' => 'Macedonia',"currency"=>'MKD','currency_is_active'=>0],
			['prefix' => 'MG', 'name' => 'Madagascar',"currency"=>'MGA','currency_is_active'=>0],
			['prefix' => 'MW', 'name' => 'Malawi',"currency"=>'MWK','currency_is_active'=>0],
			['prefix' => 'MY', 'name' => 'Malaysia',"currency"=>'MYR','currency_is_active'=>0],
			['prefix' => 'MV', 'name' => 'Maldives',"currency"=>'MVR','currency_is_active'=>0],
			['prefix' => 'ML', 'name' => 'Mali',"currency"=>'XOF','currency_is_active'=>0],
			['prefix' => 'MT', 'name' => 'Malta',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'MH', 'name' => 'Marshall Islands',"currency"=>'USD','currency_is_active'=>1],
			['prefix' => 'MQ', 'name' => 'Martinique',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'MR', 'name' => 'Mauritania',"currency"=>'MRU','currency_is_active'=>0],
			['prefix' => 'MU', 'name' => 'Mauritius',"currency"=>'MUR','currency_is_active'=>0],
			['prefix' => 'TY', 'name' => 'Mayotte',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'MX', 'name' => 'Mexico',"currency"=>'MXN','currency_is_active'=>0],
			['prefix' => 'FM', 'name' => 'Micronesia',"currency"=>'USD','currency_is_active'=>1],
			['prefix' => 'MD', 'name' => 'Moldova',"currency"=>'MDL','currency_is_active'=>0],
			['prefix' => 'MC', 'name' => 'Monaco',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'MN', 'name' => 'Mongolia',"currency"=>'MNT','currency_is_active'=>0],
			['prefix' => 'MS', 'name' => 'Montserrat',"currency"=>'XCD','currency_is_active'=>0],
			['prefix' => 'MA', 'name' => 'Morocco',"currency"=>'MAD','currency_is_active'=>0],
			['prefix' => 'MZ', 'name' => 'Mozambique',"currency"=>'MZN','currency_is_active'=>0],
			['prefix' => 'MM', 'name' => 'Myanmar',"currency"=>'MMK','currency_is_active'=>0],
			['prefix' => 'NA', 'name' => 'Namibia',"currency"=>'NAD','currency_is_active'=>0],
			['prefix' => 'NR', 'name' => 'Nauru',"currency"=>'AUD','currency_is_active'=>0],
			['prefix' => 'NP', 'name' => 'Nepal',"currency"=>'NPR','currency_is_active'=>0],
			['prefix' => 'NL', 'name' => 'Netherlands',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'NC', 'name' => 'New Caledonia',"currency"=>'XPF','currency_is_active'=>0],
			['prefix' => 'NZ', 'name' => 'New Zealand',"currency"=>'NZD','currency_is_active'=>0],
			['prefix' => 'NI', 'name' => 'Nicaragua',"currency"=>'NIO','currency_is_active'=>0],
			['prefix' => 'NE', 'name' => 'Niger',"currency"=>'XOF','currency_is_active'=>0],
			['prefix' => 'NG', 'name' => 'Nigeria',"currency"=>'NGN','currency_is_active'=>0],
			['prefix' => 'NU', 'name' => 'Niue',"currency"=>'NZD','currency_is_active'=>0],
			['prefix' => 'NF', 'name' => 'Norfork Island',"currency"=>'AUD','currency_is_active'=>0],
			['prefix' => 'MP', 'name' => 'Northern Mariana Islands',"currency"=>'USD','currency_is_active'=>1],
			['prefix' => 'NO', 'name' => 'Norway',"currency"=>'NOK','currency_is_active'=>0],
			['prefix' => 'OM', 'name' => 'Oman',"currency"=>'OMR','currency_is_active'=>0],
			['prefix' => 'PK', 'name' => 'Pakistan',"currency"=>'PKR','currency_is_active'=>0],
			['prefix' => 'PW', 'name' => 'Palau',"currency"=>'USD','currency_is_active'=>1],
			['prefix' => 'PA', 'name' => 'Panama',"currency"=>'USD','currency_is_active'=>1],
			['prefix' => 'PG', 'name' => 'Papua New Guinea',"currency"=>'PGK','currency_is_active'=>0],
			['prefix' => 'PY', 'name' => 'Paraguay',"currency"=>'PYG','currency_is_active'=>0],
			['prefix' => 'PE', 'name' => 'Peru',"currency"=>'PEN','currency_is_active'=>0],
			['prefix' => 'PH', 'name' => 'Philippines',"currency"=>'PHP','currency_is_active'=>0],
			['prefix' => 'PN', 'name' => 'Pitcairn',"currency"=>'NZD','currency_is_active'=>0],
			['prefix' => 'PL', 'name' => 'Poland',"currency"=>'PLN','currency_is_active'=>0],
			['prefix' => 'PT', 'name' => 'Portugal',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'PR', 'name' => 'Puerto Rico',"currency"=>'USD','currency_is_active'=>1],
			['prefix' => 'QA', 'name' => 'Qatar',"currency"=>'QAR','currency_is_active'=>0],
			['prefix' => 'SS', 'name' => 'Republic of South Sudan',"currency"=>'SSP','currency_is_active'=>0],
			['prefix' => 'RE', 'name' => 'Reunion',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'RO', 'name' => 'Romania',"currency"=>'RON','currency_is_active'=>0],
			['prefix' => 'RU', 'name' => 'Russian Federation',"currency"=>'RUB','currency_is_active'=>0],
			['prefix' => 'RW', 'name' => 'Rwanda',"currency"=>'RWF','currency_is_active'=>0],
			['prefix' => 'KN', 'name' => 'Saint Kitts and Nevis',"currency"=>'XCD','currency_is_active'=>0],
			['prefix' => 'LC', 'name' => 'Saint Lucia',"currency"=>'XCD','currency_is_active'=>0],
			['prefix' => 'VC', 'name' => 'Saint Vincent and the Grenadines',"currency"=>'XCD','currency_is_active'=>0],
			['prefix' => 'WS', 'name' => 'Samoa',"currency"=>'WST','currency_is_active'=>0],
			['prefix' => 'SM', 'name' => 'San Marino',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'ST', 'name' => 'Sao Tome and Principe',"currency"=>'STN','currency_is_active'=>0],
			['prefix' => 'SA', 'name' => 'Saudi Arabia',"currency"=>'SAR','currency_is_active'=>0],
			['prefix' => 'SN', 'name' => 'Senegal',"currency"=>'XOF','currency_is_active'=>0],
			['prefix' => 'RS', 'name' => 'Serbia',"currency"=>'RSD','currency_is_active'=>0],
			['prefix' => 'SC', 'name' => 'Seychelles',"currency"=>'SCR','currency_is_active'=>0],
			['prefix' => 'SL', 'name' => 'Sierra Leone',"currency"=>'SLL','currency_is_active'=>0],
			['prefix' => 'SG', 'name' => 'Singapore',"currency"=>'SGD','currency_is_active'=>0],
			['prefix' => 'SK', 'name' => 'Slovakia',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'SI', 'name' => 'Slovenia',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'SB', 'name' => 'Solomon Islands',"currency"=>'SBD','currency_is_active'=>0],
			['prefix' => 'SO', 'name' => 'Somalia',"currency"=>'SOS','currency_is_active'=>0],
			['prefix' => 'ZA', 'name' => 'South Africa',"currency"=>'ZAR','currency_is_active'=>0],
			['prefix' => 'GS', 'name' => 'South Georgia South Sandwich Islands',"currency"=>'GBP','currency_is_active'=>0],
			['prefix' => 'ES', 'name' => 'Spain',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'LK', 'name' => 'Sri Lanka',"currency"=>'LKR','currency_is_active'=>0],
			['prefix' => 'SH', 'name' => 'Saint Helena',"currency"=>'SHP','currency_is_active'=>0],
			['prefix' => 'PM', 'name' => 'Saint Pierre and Miquelon',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'SD', 'name' => 'Sudan',"currency"=>'SDG','currency_is_active'=>0],
			['prefix' => 'SR', 'name' => 'Suriname',"currency"=>'SRD','currency_is_active'=>0],
			['prefix' => 'SJ', 'name' => 'Svalbarn and Jan Mayen Islands',"currency"=>'NOK','currency_is_active'=>0],
			['prefix' => 'SZ', 'name' => 'Swaziland',"currency"=>'SZL','currency_is_active'=>0],
			['prefix' => 'SE', 'name' => 'Sweden',"currency"=>'SEK','currency_is_active'=>0],
			['prefix' => 'CH', 'name' => 'Switzerland',"currency"=>'CHF','currency_is_active'=>0],
			['prefix' => 'SY', 'name' => 'Syrian Arab Republic',"currency"=>'SYP','currency_is_active'=>0],
			['prefix' => 'TW', 'name' => 'Taiwan',"currency"=>'TWD','currency_is_active'=>0],
			['prefix' => 'TJ', 'name' => 'Tajikistan',"currency"=>'TJS','currency_is_active'=>0],
			['prefix' => 'TZ', 'name' => 'Tanzania',"currency"=>'TZS','currency_is_active'=>0],
			['prefix' => 'TH', 'name' => 'Thailand',"currency"=>'THB','currency_is_active'=>0],
			['prefix' => 'TG', 'name' => 'Togo',"currency"=>'XOF','currency_is_active'=>0],
			['prefix' => 'TK', 'name' => 'Tokelau',"currency"=>'NZD','currency_is_active'=>0],
			['prefix' => 'TO', 'name' => 'Tonga',"currency"=>'TOP','currency_is_active'=>0],
			['prefix' => 'TT', 'name' => 'Trinidad and Tobago',"currency"=>'TTD','currency_is_active'=>0],
			['prefix' => 'TN', 'name' => 'Tunisia',"currency"=>'TND','currency_is_active'=>0],
			['prefix' => 'TR', 'name' => 'Turkey',"currency"=>'TRY','currency_is_active'=>0],
			['prefix' => 'TM', 'name' => 'Turkmenistan',"currency"=>'TMT','currency_is_active'=>0],
			['prefix' => 'TC', 'name' => 'Turks and Caicos Islands',"currency"=>'USD','currency_is_active'=>1],
			['prefix' => 'TV', 'name' => 'Tuvalu',"currency"=>'AUD','currency_is_active'=>0],
			['prefix' => 'UG', 'name' => 'Uganda',"currency"=>'UGX','currency_is_active'=>0],
			['prefix' => 'UA', 'name' => 'Ukraine',"currency"=>'UAH','currency_is_active'=>0],
			['prefix' => 'AE', 'name' => 'United Arab Emirates',"currency"=>'AED','currency_is_active'=>0],
			['prefix' => 'GB', 'name' => 'United Kingdom',"currency"=>'GBP','currency_is_active'=>0],
			['prefix' => 'UY', 'name' => 'Uruguay',"currency"=>'UYU','currency_is_active'=>0],
			['prefix' => 'UZ', 'name' => 'Uzbekistan',"currency"=>'UZS','currency_is_active'=>0],
			['prefix' => 'VU', 'name' => 'Vanuatu',"currency"=>'VUV','currency_is_active'=>0],
			['prefix' => 'VA', 'name' => 'Vatican City State',"currency"=>'EUR','currency_is_active'=>1],
			['prefix' => 'VE', 'name' => 'Venezuela',"currency"=>'VES','currency_is_active'=>0],
			['prefix' => 'VN', 'name' => 'Vietnam',"currency"=>'VND','currency_is_active'=>0],
			['prefix' => 'YE', 'name' => 'Yemen',"currency"=>'YER','currency_is_active'=>0],
			['prefix' => 'YU', 'name' => 'Yugoslavia',"currency"=>'','currency_is_active'=>0],
			['prefix' => 'ZR', 'name' => 'Zaire',"currency"=>'','currency_is_active'=>0],
			['prefix' => 'ZM', 'name' => 'Zambia',"currency"=>'ZMW','currency_is_active'=>0],
			['prefix' => 'ZW', 'name' => 'Zimbabwe',"currency"=>'USD','currency_is_active'=>1],
        ];

		DB::table('countries')->insert($countries);

    }
}
