<?php

use Illuminate\Database\Seeder;
use App\Models\Country;
use App\Models\Port;

class PortSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('ports')->truncate();
        $ports = collect([
            ['AL', 'Durres (Durazzo)', 'AL DRZ'],
            ['AL', 'Sarande', 'AL SAR'],
            ['AL', 'Shengjjin', 'AL SHG'],
            ['AL', 'Vlore (Vlora, Vlone)', 'AL VOA'],
            ['DZ', 'Algiers', 'DZ ALG'],
            ['DZ', 'Annaba (Ex Bone)', 'DZ AAE'],
            ['DZ', 'Arzew', 'DZ AZW'],
            ['DZ', 'Bejaia (Ex Bougie)', 'DZ BJA'],
            ['DZ', 'Dellys', 'DZ DEL'],
            ['DZ', 'Ghazaouet', 'DZ GHA'],
            ['DZ', 'Mostaganem', 'DZ MOS'],
            ['DZ', 'Oran', 'DZ ORN'],
            ['DZ', 'Skikda (Ex Philippeville)', 'DZ SKI'],
            ['DZ', 'Tenes', 'DZ TEN'],
            ['AS', 'Pago Pago', 'AS PPG'],
            ['AO', 'Cabinda', 'AO CAB'],
            ['AO', 'Lobito', 'AO LOB'],
            ['AO', 'Luanda', 'AO LAD'],
            ['AO', 'Namibe', 'AO MSZ'],
            ['AO', 'Porto Amboim', 'AO PBN'],
            ['AO', 'Soyo', 'AO SOQ'],
            ['AR', 'Bahia Blanca', 'AR BHI'],
            ['AR', 'Buenos Aires', 'AR BUE'],
            ['AR', 'Comodoro Rivadavia', 'AR CRD'],
            ['AR', 'Concepcion del Uruguay', 'AR COU'],
            ['AR', 'Mar del Plata', 'AR MDQ'],
            ['AR', 'Necochea', 'AR NEC'],
            ['AR', 'Puerto Madryn', 'AR PMY'],
            ['AR', 'Rio Gallegos', 'AR RGL'],
            ['AR', 'Rosario', 'AR ROS'],
            ['AR', 'Santa Fe', 'AR SFN'],
            ['AR', 'Ushuaia', 'AR USH'],
            ['AW', 'Oranjestad', 'AW ORJ'],
            ['AU', 'Adelaide', 'AU PAE'],
            ['AU', 'Brisbane', 'AU BNE'],
            ['AU', 'Cairns', 'AU CNS'],
            ['AU', 'Darwin', 'AU DRW'],
            ['AU', 'Devonport', 'AU DPO'],
            ['AU', 'Fremantle', 'AU FRE'],
            ['AU', 'Geelong', 'AU GEX'],
            ['AU', 'Hobart', 'AU HBA'],
            ['AU', 'Mackay', 'AU MKY'],
            ['AU', 'Melbourne', 'AU MEL'],
            ['AU', 'Sydney', 'AU SYD'],
            ['AU', 'Townsville', 'AU TSV'],
            ['AZ', 'Baku', 'AZ BAK'],
            ['Fr', 'eport', 'BS FPO'],
            ['BS', 'Nassau', 'BS NAS'],
            ['BH', 'Mina Salman', 'BH MIN'],
            ['BH', 'Sitra', 'BH SIT'],
            ['BD', 'Chittagong', 'BD CGP'],
            ['BD', 'Mongla', 'BD MGL'],
            ['BB', 'Bridgetown', 'BB BGI'],
            ['BE', 'Antwerp', 'BE ANR'],
            ['BE', 'Brussels (Bruxelles)', 'BE BRU'],
            ['BE', 'Ghent', 'BE GNE'],
            ['BE', 'Liege', 'BE LGG'],
            ['BE', 'Zeebrugge', 'BE ZEE'],
            ['BZ', 'Belize City', 'BZ BZE'],
            ['Bj', 'Cotonou', 'BJ COO'],
            ['BM', 'Hamilton', 'BM BDA'],
            ['BM', 'St Georges', 'BM SGE'],
            ['BR', 'Belem', 'BR BEL'],
            ['BR', 'Fortaleza', 'BR FOR'],
            ['BR', 'Imbituba', 'BR IBB'],
            ['BR', 'Manaus', 'BR MAO'],
            ['BR', 'Paranagua', 'BR PNG'],
            ['BR', 'Porto Alegre', 'BR POA'],
            ['BR', 'Recife', 'BR REC'],
            ['BR', 'Rio De Janeiro', 'BR RIO'],
            ['BR', 'Rio Grande', 'BR RIG'],
            ['BR', 'Salvador', 'BR SSA'],
            ['BR', 'Santos', 'BR SSZ'],
            ['BR', 'Vitoria', 'BR VIX'],
            ['BN', 'Kuala Belait', 'BN KUB'],
            ['BN', 'Muara', 'BN MUA'],
            ['BG', 'Varna', 'BG VAR'],
            ['KH', 'Kompongsom (also known as:)', 'KH KOS'],
            ['KH', 'Phnom Penh', 'KH PNH'],
            ['CM', 'Douala', 'CM DLA'],
            ['CM', 'Kribi', 'CM KBI'],
            ['CM', 'Tiko', 'CM TKC'],
            ['CA', 'Alberni', 'CM PAB'],
            ['CA', 'Becancour', 'CA BEC'],
            ['CA', 'Churchill', 'CA CHV'],
            ['CA', 'Fraser River Port (Port of New Westminster)', 'CA NWE'],
            ['CA', 'Halifax', 'CA HAL'],
            ['CA', 'Hamilton', 'CA HAM'],
            ['CA', 'Halifax', 'CA HAL'],
            ['CA', 'Montreal', 'CA MTR'],
            ['CA', 'Nanaimo', 'CA NNO'],
            ['CA', 'Sague', 'ay	n/a'],
            ['CA', 'Sept Iles (Seven Islands)', 'CA SEI'],
            ['CA', 'St Johns', 'CA SJF'],
            ['CA', 'Sydney', 'CA SYD'],
            ['CA', 'Thunder Bay', 'CA THU'],
            ['CA', 'Toronto', 'CA TOR'],
            ['CA', 'Trois-Rivieres', 'CA TRR'],
            ['CA', 'Vancouver', 'CA VAN'],
            ['CA', 'Windsor', 'CA WND'],
            ['CV', 'Porto Grande', 'CV PGR'],
            ['KY', 'Georgetown, Grand Cayman', 'KY GEC'],
            ['CL', 'Antofagasta', 'CL ANF'],
            ['CL', 'Arica', 'CL ARI'],
            ['CL', 'Chanaral', 'CL CNR'],
            ['CL', 'Iquique', 'CL IQQ'],
            ['CL', 'Puerto Montt', 'CL PMC'],
            ['CL', 'Punta Arenas', 'CL PUQ'],
            ['CL', 'San Antonio', 'CL SAI'],
            ['CL', 'San Vicente', 'CL SVE'],
            ['CL', 'Talcahuano', 'CL TAL'],
            ['CL', 'Valparaiso', 'CL VAP'],
            ['CN', 'Dalian', 'CN DLC'],
            ['CN', 'Fuzhou', 'CN FOC'],
            ['CN', 'Guangzhou', 'CN CAN'],
            ['CN', 'Haikou', 'CN HAK'],
            ['CN', 'Lianyungang', 'CN LYG'],
            ['CN', 'Nantong', 'CN NTG'],
            ['CN', 'Ningbo', 'CN NGB'],
            ['CN', 'Qingdao', 'CN TAO'],
            ['CN', 'Qinhuangdao', 'CN SHP'],
            ['CN', 'Shanghai', 'CN SHA'],
            ['CN', 'Shantou', 'CN SWA'],
            ['CN', 'Tianjin', 'CN TSN'],
            ['CN', 'Xiamen', 'CN XMN'],
            ['CN', 'Zhanjiang', 'CN ZHA'],
            ['CO', 'Barranquilla', 'CO BAQ'],
            ['CO', 'Buenaventura', 'CO BUN'],
            ['CO', 'Cartagena', 'CO CTG'],
            ['CO', 'Puerto Bolivar', 'CO PBO'],
            ['CO', 'Tumaco', 'CO TCO'],
            ['CO', 'Turbo', 'CO TRB'],
            ['KM', 'Moroni', 'KM YVA'],
            ['KM', 'Mutsamudu', 'KM MUT'],
            ['CG', 'Pointe Noire', 'CG PNR'],
            ['CD', 'Banana', 'ZR BNW'],
            ['CD', 'Boma', 'ZR BOA'],
            ['CR', 'Caldera', 'CR CAL'],
            ['CR', 'Golfito', 'CR GLF'],
            ['CR', 'Puntarenas', 'CR PAS'],
            ['CR', 'Quepos', 'CR XQP'],
            ['HR', 'Rijeka Bakar', 'HR RJK'],
            ['HR', 'Zadar', 'HR ZAD'],
            ['HR', 'Dubrovnik', 'HR DBV'],
            ['HR', 'Omisalj', 'HR OMI'],
            ['HR', 'Ploce', 'HR PLE'],
            ['HR', 'Pula', 'HR PUY'],
            ['HR', 'Sibenik', 'HR SIB'],
            ['HR', 'Split', 'HR SPU'],
            ['CU', 'Havana', 'CU HAV'],
            ['CU', 'Manzanillo', 'CU MZO'],
            ['CU', 'Matanzas', 'CU QMA'],
            ['CU', 'Nuevitas', 'CU NVT'],
            ['CU', 'Santiago de Cuba', 'CU SCU'],
            ['CY', 'Akrotiri', 'CY AKT'],
            ['CY', 'Famagusta', 'CY FMG'],
            ['CY', 'Larnaca', 'CY LAT'],
            ['CY', 'Limassol', 'CY LMS'],
            ['CY', 'Paphos', 'CY PFO'],
            ['CY', 'Vassiliko', 'CY VAS'],
            ['DK', 'Aarhus', 'DK AAR'],
            ['DK', 'Esbjerg', 'DK EBJ'],
            ['DK', 'Fredericia', 'DK FRC'],
            ['DK', 'Frederikshavn', 'DK FDH'],
            ['DK', 'Grenaa', 'DK GRE'],
            ['DK', 'Odense', 'DK ODE'],
            ['DK', 'Ronne', 'DK RNN'],
            ['DJ', 'Djibouti', 'DJ JIB'],
            ['DM', 'Portsmouth', 'DM POR'],
            ['DM', 'Roseau', 'DM RSU'],
            ['DO', 'Barahona', 'DO BRX'],
            ['DO', 'La Romana', 'DO LRM'],
            ['DO', 'Puerto Plata', 'DO POP'],
            ['DO', 'Rio Haina', 'DO HAI'],
            ['DO', 'San Pedro de Macoris', 'DO SPM'],
            ['DO', 'Santo Domingo', 'DO SDQ'],
            ['EC', 'Esmeraldas', 'EC ESM'],
            ['EC', 'Guayaquil', 'EC GYE'],
            ['EC', 'La Libertad', 'EC LLD'],
            ['EC', 'Manta', 'EC MEC'],
            ['EC', 'Puerto Bolivar', 'EC PBO'],
            ['EC', 'San Lorenzo', 'EC SLR'],
            ['EG', 'Alexandria', 'EG EDK'],
            ['EG', 'Damietta', 'EG DAM'],
            ['EG', 'Port Said', 'EG PSD'],
            ['EG', 'Suez', 'EG'],
            ['SV', 'Acajutla', 'SV AQJ'],
            ['SV', 'Cutuco', 'SV CUT'],
            ['GQ', 'Bata', 'GQ BSG'],
            ['GQ', 'Ceiba Marine Termi', 'al n/a'],
            ['GQ', 'Malabo (Rey Malabo)', 'GQ SSG'],
            ['EE', 'Pärnu', 'EE PYA'],
            ['EE', 'Tallinn', 'EE TLL'],
            ['FO', 'Klaksvik', 'FO KVI'],
            ['FO', 'Torshavn', 'FO THO'],
            ['FJ', 'Labasa (Lambasa)', 'FJ LBS'],
            ['FJ', 'Lautoka', 'FJ LTK'],
            ['FJ', 'Levuka', 'FJ LEV'],
            ['FJ', 'Savu Savu', 'FJ SVU'],
            ['FJ', 'Suva', 'FJ SUV'],
            ['FI', 'Hamina', 'FI HMN'],
            ['FI', 'Helsinki', 'FI HEL'],
            ['FI', 'Kokkola', 'FI KOK'],
            ['FI', 'Kotka', 'FI KTK'],
            ['FI', 'Loviisa', 'FI LOV'],
            ['FI', 'Oulu', 'FI OUL'],
            ['FI', 'Pori', 'FI POR'],
            ['FI', 'Rauma', 'FI RAU'],
            ['FI', 'Turku', 'FI TKU'],
            ['FI', 'Uusikaupunki', 'FI UKI'],
            ['FI', 'Vaasa', 'FI VAA'],
            ['FR', 'Bordeaux', 'FR BOD'],
            ['FR', 'Boulogne Sur Mer', 'FR BOL'],
            ['FR', 'Cherbourg', 'FR CER'],
            ['FR', 'Dunkerque', 'FR DKK'],
            ['FR', 'La Rochelle-Pallice', 'FR LPE'],
            ['FR', 'Le Havre', 'FR LEH'],
            ['FR', 'Marseille', 'FR MRS'],
            ['FR', 'Nantes-St. Nazaire', 'FR NTE'],
            ['FR', 'Paris', 'FR PAR'],
            ['FR', 'Rouen', 'FR URO'],
            ['FR', 'St Malo', 'FR SML'],
            ['FR', 'Strasbourg', 'FR SXB'],
            ['FR', 'Toulon', 'FR TLN'],
            ['GF', 'Cayenne', 'GF CAY'],
            ['PF', 'Papeete', 'PF PPT'],
            ['GA', 'Cap Lopez', 'GA CLZ'],
            ['GA', 'Libreville', 'GA LBV'],
            ['GA', 'Owendo', 'GA OWE'],
            ['GA', 'Port Gentil', 'GA POG'],
            ['GM', 'Banjul', 'GM BJL'],
            ['GE', 'Batumi', 'GE BUS'],
            ['GE', 'Poti', 'GE PTI'],
            ['GE', 'Sukhumi', 'GE SUI'],
            ['DE', 'Brake', 'DE BKE'],
            ['DE', 'Bremen', 'DE BRE'],
            ['DE', 'Bremerhaven', 'DE BRV'],
            ['DE', 'Duisburg', 'DE DUI'],
            ['DE', 'Dusseldorf', 'DE DUS'],
            ['DE', 'Emden', 'DE EME'],
            ['DE', 'Hamburg', 'DE HAM'],
            ['DE', 'Karlsruhe', 'DE KAE'],
            ['DE', 'Kiel', 'DE KEL'],
            ['DE', 'Lubeck', 'DE LBC'],
            ['DE', 'Mannheim', 'DE MHG'],
            ['DE', 'Rostock', 'DE RSK'],
            ['DE', 'Wilhelmshavn', 'DE WVN'],
            ['GH', 'Takoradi', 'GH TKD'],
            ['GH', 'Tema', 'GH TEM'],
            ['GI', 'Gibraltar', 'GI GIB'],
            ['GR', 'Eleusis', 'GR EEU'],
            ['GR', 'Iraklion (Heraklion)', 'GR HER'],
            ['GR', 'Kavala', 'GR KVA'],
            ['GR', 'Patras', 'GR GPA'],
            ['GR', 'Piraeus', 'GR PIR'],
            ['GR', 'Thessaloniki', 'GR SKG'],
            ['GR', 'Volos', 'GR VOL'],
            ['GL', 'Holsteinsborg (Sisimiut)', 'GL JHS'],
            ['GL', 'Nanortalik', 'GL JNN'],
            ['GL', 'Narsarsuaq', 'GL UAK'],
            ['GL', 'Nuuk (Godthaab)', 'GL GOH'],
            ['GP', 'Gustavia', 'GP GUS'],
            ['GP', 'Pointe-a-Pitre', 'GP PTP'],
            ['GU', 'Apra (Agana)', 'GU APR'],
            ['GT', 'Champerico', 'GT CHR'],
            ['GT', 'Puerto Barrios', 'GT PBR'],
            ['GT', 'Santo Tomas De Castilla', 'GT STC'],
            ['GN', 'Conakry', 'GN CKY'],
            ['GN', 'Port Kamsar', 'GN KMR'],
            ['GW', 'Bissau', 'GW BXO'],
            ['GY', 'Georgetown', 'GY GEO'],
            ['GY', 'New Amsterdam', 'GY QSK'],
            ['HT', 'Port Au Prince', 'HT PAP'],
            ['HN', 'La Ceiba', 'HN LCE'],
            ['HN', 'Puerto Castilla', 'HN PCA'],
            ['HN', 'Puerto Cortes', 'HN PCR'],
            ['HN', 'San Lorenzo', 'HN SLO'],
            ['HN', 'Tela', 'HN TEA'],
            ['HK', 'Hong Kong', 'HK HKG'],
            ['IS', 'Akureyri', 'IS AKU'],
            ['IS', 'Hafnarfjordur (Straumsvik)', 'IS HAF'],
            ['IS', 'Isafjordur', 'IS ISA'],
            ['IS', 'Keflavik', 'IS KEV'],
            ['IS', 'Reykjavik', 'IS REY'],
            ['IS', 'Vestmannaeyjar', 'IS VES'],
            ['IN', 'Bombay (Mumbai)', 'IN BOM'],
            ['IN', 'Calcutta (Kolkata)', 'IN CCU'],
            ['IN', 'Chennai (Madras)', 'IN MAA'],
            ['IN', 'Cochin', 'IN COK'],
            ['IN', 'Kandla', 'IN IXY'],
            ['IN', 'Nhava Sheva (Jawaharlal Nehru)', 'IN NSA'],
            ['IN', 'Tuticorin', 'IN TUT'],
            ['IN', 'Vishakhapatnam', 'IN VTZ'],
            ['ID', 'Cilacap, Java(Tanjung Intan)', 'ID CXP'],
            ['ID', 'Cirebon, Java', 'ID CBN'],
            ['ID', 'Jakarta, Java (Tanjung Priok)', 'ID TPP'],
            ['ID', 'Kupang, Timor', 'ID KOE'],
            ['ID', 'Palembang, Sumatra', 'ID PLM'],
            ['ID', 'Semarang, Java (Tanjung Emas)', 'ID SRG'],
            ['ID', 'Surabaya, Java (Tanjung Perak)', 'ID SUB'],
            ['ID', 'Ujung Pandang, Sulawesi (Makassar)', 'ID UPG'],
            ['IR', 'Abadan', 'IR ABD'],
            ['IR', 'Bandar Abbas', 'IR BND'],
            ['IR', 'Bandar Anzali', 'IR BAZ'],
            ['IR', 'Bandar Mahshahr', 'IR MRX'],
            ['IR', 'Bushehr', 'IR BUZ'],
            ['IR', 'Imam Khomeini', 'IR BKM'],
            ['IR', 'Khorramshahr', 'IR KHO'],
            ['IR', 'Lavan', 'IR LVP'],
            ['IR', 'Sirri Island', 'IR SXI'],
            ['IQ', 'Basra', 'IQ BSR'],
            ['IQ', 'Khor al Zubair', 'IQ KAZ'],
            ['IQ', 'Umm Qasr', 'IQ UQR'],
            ['IE', 'Arklow', 'IE ARK'],
            ['IE', 'Cork', 'IE ORK'],
            ['IE', 'Drogheda', 'IE DRO'],
            ['IE', 'Dublin', 'IE DUB'],
            ['IE', 'Foynes (Shannon Foynes Port)', 'IE FOV'],
            ['IE', 'Galway', 'IE GWY'],
            ['IE', 'New Ross', 'IE NRS'],
            ['IE', 'Waterford', 'IE WAT'],
            ['IL', 'Ashdod', 'IL ASH'],
            ['IL', 'Ashkelon', 'IL AKL'],
            ['IL', 'Eilat', 'IL ETH'],
            ['IL', 'Hadera', 'IL HAD'],
            ['IL', 'Haifa', 'IL HFA'],
            ['IT', 'Augusta', 'IT AUG'],
            ['IT', 'Bagnoli', 'IT BLN'],
            ['IT', 'Bari', 'IT BRI'],
            ['IT', 'Brindisi', 'IT BDS'],
            ['IT', 'Gela', 'IT GEA'],
            ['IT', 'Genoa', 'IT GOA'],
            ['IT', 'La Spezia', 'IT SPE'],
            ['IT', 'Livorno', 'IT LIV'],
            ['IT', 'Messina', 'IT MSN'],
            ['IT', 'Milazzo', 'IT MLZ'],
            ['IT', 'Napoli (Naples)', 'IT NAP'],
            ['IT', 'Palermo', 'IT PMO'],
            ['IT', 'Porto Torres', 'IT PTO'],
            ['IT', 'Ravenna', 'IT RAN'],
            ['IT', 'Sarroch (Porto Foxi)', 'IT PFX'],
            ['IT', 'Savona-Vado', 'IT SVN'],
            ['IT', 'Taranto', 'IT TAR'],
            ['IT', 'Trieste', 'IT TRS'],
            ['IT', 'Venice', 'IT VCE'],
            ['JM', 'Kingston', 'JM KIN'],
            ['JM', 'Montego Bay', 'JM MBJ'],
            ['JM', 'Ocho Rios', 'JM OCJ'],
            ['JM', 'Port Antonio', 'JM POT'],
            ['JM', 'Port Esquivel', 'JM PEV'],
            ['JM', 'Rocky Point', 'JM ROP'],
            ['JP', 'Akita', 'JP AXT'],
            ['JP', 'Amagasaki', 'JP AMA'],
            ['JP', 'Chiba', 'JP CHB'],
            ['JP', 'Hachinohe', 'JP HHE'],
            ['JP', 'Hakodate, Hokkaido', 'JP HKD'],
            ['JP', 'Higashiharima', 'JP HHR'],
            ['JP', 'Himeji', 'JP HIM'],
            ['JP', 'Hiroshima', 'JP HIJ'],
            ['JP', 'Kawasaki', 'JP KWS'],
            ['JP', 'Kinuura', 'JP KNU'],
            ['JP', 'Kobe', 'JP UKB'],
            ['JP', 'Kushiro, Hokkaido', 'JP KUH'],
            ['JP', 'Mizushima', 'JP MIZ'],
            ['JP', 'Moji', 'JP MOJ'],
            ['JP', 'Nagoya', 'JP NGO'],
            ['JP', 'Osaka', 'JP OSA'],
            ['JP', 'Sakai', 'JP SAK'],
            ['JP', 'Sakata', 'JP SKT'],
            ['JP', 'Shimizu', 'JP SMZ'],
            ['JP', 'Tokyo', 'JP TYO'],
            ['JP', 'Tomakomai,Hokkaido', 'JP TMK'],
            ['JP', 'Yokohama', 'JP YOK'],
            ['JP', 'Aqaba (El Akaba)', 'JO AQJ'],
            ['KE', 'Lamu', 'KE LAU'],
            ['KE', 'Mombasa', 'KE MBA'],
            ['KI', 'Betio (Tarawa)', 'KI TRW'],
            ['KP', 'Chongjin', 'KP CHO'],
            ['KP', 'Haeju', 'KP HAE'],
            ['KP', 'Nampo', 'KP NAM'],
            ['KP', 'Wonsan', 'KP WON'],
            ['KR', 'Busan (Pusan)', 'KR PUS'],
            ['KR', 'Chinhae', 'KR CHF'],
            ['KR', 'Inchon', 'KR INC'],
            ['KR', 'Masan', 'KR MAS'],
            ['KR', 'Mokpo', 'KR MOK'],
            ['KR', 'Pohang', 'KR KPO'],
            ['KR', 'Tonghae', 'KR TGH'],
            ['KR', 'Ulsan', 'KR USN'],
            ['KR', 'Yosu (Yeosu)', 'KR YOS'],
            ['KW', 'Mina al Ahmadi', 'KW MEA'],
            ['KW', 'Mina Saud', 'KW MIS'],
            ['KW', 'Shuwaikh', 'KW SWK'],
            ['LV', 'Liepaja', 'LV LPX'],
            ['LV', 'Riga', 'SU RIX'],
            ['LV', 'Ventspils', 'LV VNT'],
            ['LB', 'Beirut', 'LB BEY'],
            ['LB', 'Chekka', 'LB CHK'],
            ['LB', 'Selaata', 'LB SEL'],
            ['LB', 'Sidon', 'LB SDN'],
            ['LB', 'Tripoli', 'LB KYE'],
            ['LR', 'Buchanan', 'LR UCN'],
            ['LR', 'Greenville', 'LR GRE'],
            ['LR', 'Monrovia', 'LR MLW'],
            ['LY', 'Bingazi (Benghazi)', 'LY BEN'],
            ['LY', 'Derna', 'LY DNF'],
            ['LY', 'Marsa El Brega', 'LY LMQ'],
            ['LY', 'Misurata (Qasr Ahmed)', 'LY MRA'],
            ['LY', 'Ras Lanuf', 'LY RLA'],
            ['LY', 'Tobruk', 'LY TOB'],
            ['LY', 'Tripoli', 'LY TIP'],
            ['LY', 'Zuara', 'LY ZUA'],
            ['LT', 'Klaipeda (includes sixsubports:)', 'LT KLJ'],
            ['MO', 'Macau (Macao, Aomen', '	MOMFM'],
            ['MG', 'Antsiranana (Diego Suarez)', 'MG DIE'],
            ['MG', 'Majunga (Mahajanga)', 'MG MJN'],
            ['MG', 'Toamasina (Tamatave)', 'MG TOA'],
            ['MG', 'Tulear (Toliara)', 'MG TLE'],
            ['MY', 'Bintulu, Sarawak', 'MY BTU'],
            ['MY', 'Kota Kinabalu, Sabah', 'MY BKI'],
            ['MY', 'Kuantan (Tanjong Gelang)', 'MY KUA'],
            ['MY', 'Kuching, Sarawak', 'MY KCH'],
            ['MY', 'Kudat, Sabah', 'MY KUD'],
            ['MY', 'Labuan, Sabah', 'MY LBU'],
            ['MY', 'Lahad Datu, Sabah', 'MY LDU'],
            ['MY', 'Lumut', 'MY LUM'],
            ['MY', 'Miri, Sarawak', 'MY MYY'],
            ['MY', 'Pasir Gudang, Johor', 'MY PGU'],
            ['MY', 'Penang (Georgetown)', 'MY PEN'],
            ['MY', 'Port Dickson', 'MY PDI'],
            ['MY', 'Port Klang (Kelang)', 'MY PKL'],
            ['MY', 'Sandakan, Sabah', 'MY SDK'],
            ['MY', 'Sibu, Sarawak', 'MY SBW'],
            ['MY', 'Tanjung Pelepas,Johor', 'MY TPP'],
            ['MY', 'Tawau, Sabah', 'MY TWU'],
            ['MT', 'Valletta', 'MT MLA'],
            ['MQ', 'Fort de France', 'MQ FDF'],
            ['MR', 'Nouadhibou', 'MR NDB'],
            ['MR', 'Nouakchott', 'MR NKC'],
            ['MU', 'Port Louis', 'MU PLU'],
            ['MX', 'Acapulco', 'MX ACA'],
            ['MX', 'Coatzacoalcos', 'MX COA'],
            ['MX', 'Guaymas', 'MX GYM'],
            ['MX', 'La Paz', 'MX LAP'],
            ['MX', 'Lazaro Cardenas', 'MX LZC'],
            ['MX', 'Manzanillo', 'MX ZLO'],
            ['MX', 'Mazatlan', 'MX MZT'],
            ['MX', 'Progreso', 'MX PGO'],
            ['MX', 'Salina Cruz', 'MX SCX'],
            ['MX', 'Tampico', 'MX TAM'],
            ['MX', 'Topolobampo', 'MX TPB'],
            ['MX', 'Tuxpan', 'MX TUX'],
            ['MX', 'Veracruz', 'MX VER'],
            ['FM', 'Pohnpei (Ex Ponape)', 'FM PNI'],
            ['MC', 'Monaco', 'MC MON'],
            ['MS', 'Plymouth', 'MS PLY'],
            ['MA', 'Agadir', 'MA AGA'],
            ['MA', 'Casablanca', 'MA CAS'],
            ['MA', 'El Jadida', 'MA ELJ'],
            ['MA', 'Kenitra', 'MA NNA'],
            ['MA', 'Mohammedia', 'MA MOH'],
            ['MA', 'Safi', 'MA SFI'],
            ['MA', 'Tangier', 'MA TNG'],
            ['MZ', 'Beira', 'MZ BEW'],
            ['MZ', 'Inhambane', 'MZ INH'],
            ['MZ', 'Maputo', 'MZ MPM'],
            ['MZ', 'Nacala', 'MZ MNC'],
            ['MZ', 'Pemba', 'MZ POL'],
            ['MZ', 'Quelimane', 'MZ UEL'],
            ['MZ', 'Bassein', 'MM BSX'],
            ['MM', 'Moulmein', 'MM MNU'],
            ['MM', 'Yangon', 'MM RGN'],
            ['NA', 'Luderitz', 'NA LUD'],
            ['NA', 'Walvis Bay', 'NA WVB'],
            ['NR', 'Nauru Island', 'NR INU'],
            ['NL', 'Amsterdam', 'NL AMS'],
            ['NL', 'Delfzijl', 'NL DZL'],
            ['NL', 'Dordrecht', 'NL DOR'],
            ['NL', 'Eemshaven', 'NL EEM'],
            ['NL', 'Groningen', 'NL GRQ'],
            ['NL', 'IJmuiden', 'NL IJM'],
            ['NL', 'Rotterdam', 'NL RTM'],
            ['NL', 'Terneuzen', 'NL TNZ'],
            ['NL', 'Kralendijk, Bonaire', 'AN KRA'],
            ['NL', 'Philipsburg', 'AN PHI'],
            ['NL', 'Willemstad', 'AN WIL'],
            ['NC', 'Noumea', 'NC NOU'],
            ['MC', 'Thio', 'NC THI'],
            ['NZ', 'Auckland Otago Harbour', 'NZ AKL'],
            ['NZ', '(Dunedin, Port Chalmers, Ravensbourne)', 'NZ ORR'],
            ['NZ', 'Tauranga', 'NZ TRG'],
            ['NZ', 'Wellington', 'NZ WLG'],
            ['NI', 'Bluefields', 'NI BEF'],
            ['NI', 'Corinto', 'NI CIO'],
            ['NI', 'El Bluff', 'NI ELB'],
            ['NI', 'Puerto Cabezas', 'NI PUZ'],
            ['NI', 'Puerto Sandino', 'NI PSN'],
            ['NI', 'San Juan Del Sur', 'NI SJS'],
            ['NE', 'Calabar', 'NG CBQ'],
            ['NE', 'Lagos', 'NG LOS'],
            ['NE', 'Onne', 'NG ONN'],
            ['NE', 'Port Harcourt', 'NG PHC'],
            ['NE', 'Sapele', 'NG SPL'],
            ['NE', 'Tin Can Island', 'NG TIN'],
            ['NE', 'Warri', 'NG WAR'],
            ['MP', 'Saipan', 'MP SPN'],
            ['NO', 'Bergen', 'NO BGO'],
            ['NO', 'Drammen', 'NO DRM'],
            ['NO', 'Grenland Harbour (Rafnes, Hero', 'a)	n/a'],
            ['NO', 'Hammerfest', 'NO HFT'],
            ['NO', 'Harstad', 'NO HRD'],
            ['NO', 'Haugesund', 'NO HAU'],
            ['NO', 'Kristiansand', 'NO KRS'],
            ['NO', 'Larvik', 'NO LAR'],
            ['NO', 'Oslo', 'NO OSL'],
            ['NO', 'Stavanger', 'NO SVG'],
            ['NO', 'Trondheim', 'NO TRD'],
            ['PK', 'Karachi', 'PK KHI'],
            ['PK', 'Muhammad Bin Qasim', 'PK BQM'],
            ['PA', 'Colon', 'PA ONX'],
            ['PA', 'Cristobal', 'PA CTB'],
            ['PA', 'Vacamonte', 'PA VAC'],
            ['PG', 'Kieta', 'PG KIE'],
            ['PG', 'Lae', 'PG LAE'],
            ['PG', 'Madang', 'PG MAG'],
            ['PG', 'Port Moresby', 'PG POM'],
            ['PG', 'Rabaul', 'PG RAB'],
            ['PE', 'Callao', 'PE CLL'],
            ['PE', 'Chimbote', 'PE CHM'],
            ['PE', 'Ilo', 'PE ILO'],
            ['PE', 'Matarani', 'PE MRI'],
            ['PE', 'Paita', 'PE PAI'],
            ['PE', 'Salaverry', 'PE SVY'],
            ['PE', 'Talara', 'PE TYL'],
            ['PH', 'Batangas', 'PH BTG'],
            ['PH', 'Cagayan de Oro, Mindanao', 'PH CGY'],
            ['PH', 'Cebu', 'PH CEB'],
            ['PH', 'Davao, Mindanao', 'PH DVO'],
            ['PH', 'Iligan, Mindanao', 'PH IGN'],
            ['PH', 'Iloilo', 'PH ILO'],
            ['PH', 'Jolo', 'PH JOL'],
            ['PH', 'Legaspi, Davao', 'PH LGP'],
            ['PH', 'Manila', 'PH MNL'],
            ['PH', 'Puerto Princesa,Palawan', 'PH PPS'],
            ['PH', 'San Fernando, Luzon', 'PH SFE'],
            ['PH', 'Subic Bay', 'PH SFS'],
            ['PH', 'Zamboanga, Mindanao', 'PH ZAM'],
            ['PL', 'Gdansk', 'PL GDN'],
            ['PL', 'Gdynia', 'PL GDY'],
            ['PL', 'Kolobrzeg', 'PL KOL'],
            ['PL', 'Swinoujscie', 'PL SWI'],
            ['PL', 'Szczecin', 'PL SZZ'],
            ['PL', 'Ustka', 'PL UST'],
            ['PT', 'Aveiro', 'PT AVE'],
            ['PT', 'Leixoes', 'PT LEI'],
            ['PT', 'Lisbon', 'PT LIS'],
            ['PT', 'Portimao', 'PT PRM'],
            ['PT', 'Setubal', 'PT SET'],
            ['PT', 'Viana Do Castelo', 'PT VDC'],
            ['PR', 'Guanica Harbour', 'PR GUX'],
            ['PR', 'Guayanilla', 'PR GUY'],
            ['PR', 'Las Mareas', 'PR LAM'],
            ['PR', 'Ponce', 'PR PSE'],
            ['PR', 'San Juan', 'PR SJU'],
            ['QA', 'Doha', 'QA DOH'],
            ['QA', 'Halul Island', 'QA HAL'],
            ['QA', 'Ras Laffan', 'QA RLF'],
            ['QA', 'Umm Said (Mesaieed)', 'QA UMS'],
            ['RE', 'Port Reunion (Pointe des Galets)', 'RE PDG'],
            ['RO', 'Braila', 'RO BRA'],
            ['RO', 'Constantza', 'RO CND'],
            ['RO', 'Mangalia', 'RO MAG'],
            ['RO', 'Sulina', 'RO SUL'],
            ['RU', 'Kaliningrad', 'SU KGD'],
            ['RU', 'Kholmsk', 'RU KHO'],
            ['RU', 'Murmansk', 'RU MMK'],
            ['RU', 'Nakhodka', 'RU NJK'],
            ['RU', 'Novorossiysk', 'RU NVS'],
            ['RU', 'St Petersburg', 'RU LED'],
            ['RU', 'Tuapse', 'RU TUA'],
            ['RU', 'Vladivostok', 'RU VVO'],
            ['RU', 'Vyborg', 'RU VYG'],
            ['KN', 'Basseterre', 'KN BAS'],
            ['LC', 'Castries (St Lucia)', 'LC SLU'],
            ['LC', 'Vieux Fort', 'LC VIF'],
            ['VC', 'Kingstown', 'VC KTN'],
            ['WS', 'Apia', 'WS APW'],
            ['ST', 'Santo Antonio', 'ST SAA'],
            ['ST', 'Sao Tome', 'ST TMS'],
            ['SA', 'Dammam', 'SA DMN'],
            ['SA', 'Dhuba', 'SA DHU'],
            ['SA', 'Gizan', 'SA GIZ'],
            ['SA', 'Jeddah', 'SA JED'],
            ['SA', 'Jubail', 'SA JUB'],
            ['SA', 'Rabigh', 'SA RAB'],
            ['SA', 'Ras al Mishab', 'SA RAM'],
            ['SA', 'Ras Tanura', 'SA RTA'],
            ['SA', 'Yanbu', 'SA YNB'],
            ['SN', 'Dakar', 'SN DKR'],
            ['SC', 'Port Victoria', 'SC POV'],
            ['SL', 'Freetown', 'SL FNA'],
            ['SL', 'Pepel', 'SL PEP'],
            ['SG', 'Singapore', 'SG SIN'],
            ['SK', 'Izola', 'SI IZO'],
            ['SK', 'Koper', 'SI KOP'],
            ['SK', 'Piran', 'SI PIR'],
            ['SB', 'Honiara', 'SB HIR'],
            ['SB', 'Noro, New Georgia', 'SB NOR'],
            ['SB', 'Viru Harbour', 'SB VIU'],
            ['SB', 'Yandina, Pavuvu Island', 'SB XYA'],
            ['SO', 'Berbera', 'SO BBO'],
            ['SO', 'Kismayu', 'SO KMU'],
            ['SO', 'Merca', 'SO MER'],
            ['SO', 'Mogadishu', 'SO MGQ'],
            ['ZA', 'Cape Town', 'ZA CPT'],
            ['ZA', 'Durban', 'ZA DUR'],
            ['ZA', 'Mossel Bay', 'ZA MZY'],
            ['ZA', 'Port Elizabeth', 'ZA PLZ'],
            ['ZA', 'Richards Bay', 'ZA RCB'],
            ['ZA', 'Saldanha Bay', 'ZA SDB'],
            ['ES', 'Aviles', 'ES AVS'],
            ['ES', 'Barcelona', 'ES BCN'],
            ['ES', 'Bilbao', 'ES BIO'],
            ['ES', 'Cadiz', 'ES CAD'],
            ['ES', 'Cartagena', 'ES CAR'],
            ['ES', 'Castellon', 'ES CAS'],
            ['ES', 'Ceuta', 'ES CEU'],
            ['ES', 'Huelva', 'ES HUV'],
            ['ES', 'Malaga', 'ES AGP'],
            ['ES', 'Pasajes', 'ES PAS'],
            ['ES', 'Santander', 'ES SDR'],
            ['ES', 'Tarragona', 'ES TAR'],
            ['ES', 'Valencia', 'ES VLC'],
            ['ES', 'Vigo', 'ES VGO'],
            ['LK', 'Colombo', 'LK CMB'],
            ['LK', 'Jaffna', 'LK JAF'],
            ['LK', 'Trincomalee', 'LK TRR'],
            ['SH', 'Jamestown', 'SH SHN'],
            ['PM', 'St Pierre', 'PM FSP'],
            ['SD', 'Port Sudan', 'SD PZU'],
            ['SR', 'Moengo', 'SR MOJ'],
            ['SR', 'Nieuw Nickerie', 'SR ICK'],
            ['SR', 'Paramaribo', 'SR PBM'],
            ['SR', 'Paranam', 'SR PRM'],
            ['SR', 'Wageningen', 'SR AGI'],
            ['SE', 'Gavle', 'SE GVX'],
            ['SE', 'Gothenburg (Goteborg)', 'SE GOT'],
            ['SE', 'Halmstad', 'SE HAD'],
            ['SE', 'Kalmar', 'SE KLR'],
            ['SE', 'Karlshamn', 'SE KAN'],
            ['SE', 'Malmo', 'SE MMA'],
            ['SE', 'Solvesborg', 'SE SOL'],
            ['SE', 'Stockholm', 'SE STO'],
            ['SE', 'Sundsvall', 'SE SDL'],
            ['CH', 'Basel', 'CH BSL'],
            ['SY', 'Baniyas', 'SY BAN'],
            ['TW', 'Hualien', 'TW HUN'],
            ['TW', 'Kaohsiung', 'TW KHH'],
            ['TW', 'Kaohsiung', 'TW KHH'],
            ['TW', 'Keelung (Chilung)', 'TW KEL'],
            ['TW', 'Suao', 'TW SUO'],
            ['TW', 'Taichung', 'TW TXG'],
            ['TZ', 'Dar Es Salaam', 'TZ DAR'],
            ['TZ', 'Kilwa Masoko', 'TZ KIM'],
            ['TZ', 'Lindi', 'TZ LDI'],
            ['TZ', 'Mtwara', 'TZ MYW'],
            ['TZ', 'Pangani', 'TZ PAN'],
            ['TZ', 'Tanga', 'TZ TGT'],
            ['TH', 'Bangkok', 'TH BKK'],
            ['TH', 'Laem Chabang', 'TH LCH'],
            ['TH', 'Pattani', 'TH PAN'],
            ['TH', 'Phuket', 'TH HKT'],
            ['TH', 'Sattahip', 'TH SAT'],
            ['TH', 'Songkhla', 'TH SGZ'],
            ['TH', 'Sriracha', 'TH SRI'],
            ['TG', 'Kpeme', 'TG KPE'],
            ['TG', 'Lome', 'TG LFW'],
            ['TO', 'Neiafu', 'TO NEI'],
            ['TO', 'Nukualofa', 'TO TBU'],
            ['TO', 'Pangai', 'TO PAN'],
            ['TT', 'Point Fortin', 'TT PTF'],
            ['TT', 'Point Lisas', 'TT PTS'],
            ['TT', 'Pointe a Pierre', 'TT PTP'],
            ['TT', 'Scarborough', 'TT SCA'],
            ['TT', 'Spain', 'TT POS'],
            ['TT', 'Tembladora', 'TT TEM'],
            ['TN', 'Bizerte', 'TN BIZ'],
            ['TN', 'Gabes', 'TN GAE'],
            ['TN', 'La Goulette', 'TN LGN'],
            ['TN', 'Sfax', 'TN SFA'],
            ['TN', 'Sousse', 'TN SUS'],
            ['TN', 'Tunis', 'TN TUN'],
            ['TR', 'Derince', 'TR DRC'],
            ['TR', 'Dikili', 'TR DIK'],
            ['TR', 'Gemlik', 'TR GEM'],
            ['TR', 'Hopa, Artvin', 'TR HOP'],
            ['TR', 'Iskenderun, Hatay', 'TR ISK'],
            ['TR', 'Istanbul', 'TR IST'],
            ['TR', 'Trabzon', 'TR TZX'],
            ['TC', 'Grand Turk Island', 'TC GDT'],
            ['TC', 'Providenciales', 'TC PLS'],
            ['TV', 'Funafuti', 'TV FUN'],
            ['UA', 'Berdyansk', 'UA ERD'],
            ['UA', 'Kherson', 'UA KHE'],
            ['UA', 'Odessa', 'UA ODS'],
            ['UA', 'Reni', 'UA RNI'],
            ['UA', 'Sevastopol', 'UA SVP'],
            ['AE', 'Ajman', 'AE AJM'],
            ['AE', 'Das Island', 'AE DAS'],
            ['AE', 'Dubai (Port Rashid)', 'AE DXB'],
            ['AE', 'Fujairah', 'AE FJR'],
            ['AE', 'Jebel Dhanna/Ruwais', 'AE JEA'],
            ['AE', 'Khor Fakkan', 'AE KLF'],
            ['AE', 'Mina Saqr', 'AE MSA'],
            ['AE', 'Mina Zayed', 'AE MZD'],
            ['GB', 'Aberdeen', 'GB ABD'],
            ['GB', 'Belfast', 'GB BEL'],
            ['GB', 'Bristol', 'GB BRS'],
            ['GB', 'Dover', 'GB DVR'],
            ['GB', 'Falmouth', 'GB FAL'],
            ['GB', 'Felixstowe', 'GB FXT'],
            ['GB', 'Glasgow', 'GB GLW'],
            ['GB', 'Grangemouth', 'GB GRG'],
            ['GB', 'Hull', 'GB HUL'],
            ['GB', 'Leith', 'GB LEI'],
            ['GB', 'Liverpool', 'GB LIV'],
            ['GB', 'London', 'GB LON'],
            ['GB', 'Manchester', 'GB MNC'],
            ['GB', 'Peterhead Bay', 'GB PHD'],
            ['GB', 'Plymouth', 'GB PLY'],
            ['GB', 'Portsmouth', 'GB PME'],
            ['GB', 'Scapa Flow', 'GB SFW'],
            ['GB', 'Southampton', 'GB SOU'],
            ['GB', 'Sullom Voe', 'GB SUL'],
            ['GB', 'Teesport', 'GB TEE'],
            ['GB', 'Thamesport', 'GB RCS'],
            ['GB', 'Tyne', 'GB TYN'],
            ['US', 'Anacortes', 'US AOT'],
            ['US', 'Ashtabula', 'US ASF'],
            ['US', 'Baltimore', 'US BAL'],
            ['US', 'Baton Rouge', 'US BTR'],
            ['US', 'Beaumont', 'US BPT'],
            ['US', 'Boston', 'US BOS'],
            ['US', 'Charleston', 'US CHS'],
            ['US', 'Chicago', 'US CHI'],
            ['US', 'Cleveland', 'US CLE'],
            ['US', 'Corpus Christi', 'US CRP'],
            ['US', 'Detroit', 'US DET'],
            ['US', 'Duluth-Superior', 'US DLH'],
            ['US', 'Freeport', 'US FRP'],
            ['US', 'Hampton Roads (Norfolk, Chesapeake)', 'US HNV'],
            ['US', 'Honolulu', 'US HNL'],
            ['US', 'Houston', 'US HOU'],
            ['US', 'Huntington - Tri-State (WV)', 'US HTS'],
            ['US', 'Jacksonville', 'US JAX'],
            ['US', 'Lake Charles', 'US LCH'],
            ['US', 'Long Beach', 'US LGB'],
            ['US', 'Los Angeles', 'US LAX'],
            ['US', 'Manatee', 'US MEE'],
            ['US', 'Memphis', 'US MEM'],
            ['US', 'Miami', 'US MIA'],
            ['US', 'Mobile', 'US MOB'],
            ['US', 'New Orl', 'ans	US'],
            ['US', 'New York/New Jersey', 'US NYC'],
            ['US', 'Oakland', 'US OAK'],
            ['US', 'Pascagoula', 'US PGL'],
            ['US', 'Philadelphia', 'US PHL'],
            ['US', 'Pittsburgh', 'US PIT'],
            ['US', 'Plaquemines (Louisiana)', 'US PLQ'],
            ['US', 'Port Arthur', 'US POA'],
            ['US', 'Port Everglades', 'US PEF'],
            ['US', 'Portland (Maine)', 'US PWM'],
            ['US', 'Portland (Oregon)', 'US PDX'],
            ['US', 'Richmond (CA)', 'US RCH'],
            ['US', 'Richmond (VA)', 'US RIC'],
            ['US', 'Savannah', 'US SAV'],
            ['US', 'Seattle', 'US SEA'],
            ['US', 'South Louisiana', 'US LUA'],
            ['US', 'Tacoma', 'US ACI'],
            ['US', 'Tampa', 'US TPA'],
            ['US', 'Texas City', 'US TXT'],
            ['US', 'Valdez', 'US VDZ'],
            ['US', 'Wilmington (DE)', 'US ILM'],
            ['US', 'Wilmington (NC)', 'US ILG'],
            ['US', 'Yakutat', 'US YAK'],
            ['UY', 'Fray Bentos', 'UY FZB'],
            ['UY', 'Montevideo', 'UY MVD'],
            ['UY', 'Nueva Palmira', 'UY NVP'],
            ['UY', 'Paysandu', 'UY PDU'],
            ['VU', 'Port Vila', 'VU VLI'],
            ['VU', 'Santo', 'VU SAN'],
            ['VE', 'Bajo Grande Refinery', 'VE BJV'],
            ['VE', 'Cumana (Puerto Sucre)', 'VE CUM'],
            ['VE', 'La Guaira', 'VE LAG'],
            ['VE', 'La Salina', 'VE LSV'],
            ['VE', 'Maracaibo', 'VE MAR'],
            ['VE', 'Matanzas', 'VE MTV'],
            ['VE', 'Palua', 'VE PLA'],
            ['VE', 'Puerto Cabello', 'VE PBL'],
            ['VE', 'Puerto La Cruz', 'VE PCZ'],
            ['VE', 'Punta Cardon', 'VE PCN'],
            ['VN', 'Danang', 'VN DAD'],
            ['VN', 'Haiphong', 'VN HPH'],
            ['VN', 'Ho Chi Minh City', 'VN SGN'],
            ['VN', 'Hon Gay', 'VN HON'],
            ['VN', 'Nha Trang', 'VN NHA'],
            ['YE', 'Aden', 'YE ADE'],
            ['YE', 'Hodeidah', 'YE HOD'],
            ['YE', 'Mokha', 'YE MOK'],
            ['YE', 'Mukalla', 'YE MKX'],
        ]);
        $ports = $ports->map(function($item){
            $Country = Country::where('prefix',$item[0])->first();
            return [$Country->id,$item[1],$item[2]];
        })->filter(function($item){
            return !is_null($item[0]);
        })->map(function($item){
            return [
                'name'=>$item[1],
                'country_id'=>$item[0],
                'code'=>$item[2]
            ];
        })->each(function($item){
            Port::create($item);
        });

        //DB::table('ports')->insert($ports->all());


    }
}
